# Generated by Django 2.1.2 on 2018-10-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='totalDislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact',
            name='totalLikes',
            field=models.IntegerField(default=0),
        ),
    ]
