# Generated by Django 2.1.2 on 2018-10-28 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fc', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(1, 'True'), (0, 'Sort Of True'), (-1, 'False')], verbose_name='vote')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='totalFalses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='totalSortOfs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='totalTrues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fc.Comment'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
