# Generated by Django 2.1.2 on 2018-12-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc', '0007_reportcomment_reportfact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcomment',
            name='reason',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reportfact',
            name='reason',
            field=models.TextField(max_length=300),
        ),
    ]
