# Generated by Django 2.1.2 on 2018-12-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc', '0009_auto_20181202_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcomment',
            name='investigated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportfact',
            name='investigated',
            field=models.BooleanField(default=False),
        ),
    ]
